import mock from '../mock';
import user1 from 'src/assets/images/profile/user-1.jpg';
import user2 from 'src/assets/images/profile/user-2.jpg';
import user3 from 'src/assets/images/profile/user-3.jpg';
import user4 from 'src/assets/images/profile/user-4.jpg';
import user5 from 'src/assets/images/profile/user-5.jpg';

export const ContactList = [
  {
    id: 1,
    firstname: 'Ana',
    lastname: 'Silva',
    image: user2,
    department: 'Vendas',
    company: 'Imobiliária Muller',
    phone: '(11) 9 9876-5432',
    email: 'ana.silva@gmail.com',
    address: 'Rua das Flores, 123, São Paulo, SP, 01234-567',
    notes: 'Especialista em imóveis de luxo',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 2,
    firstname: 'Carlos',
    lastname: 'Oliveira',
    image: user3,
    department: 'Suporte',
    company: 'Imobiliária Zboncak',
    phone: '(21) 9 8765-4321',
    email: 'carlos.oliveira@hotmail.com',
    address: 'Avenida Paulista, 1000, São Paulo, SP, 01310-100',
    notes: 'Especialista em financiamento imobiliário',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
  },
  {
    id: 3,
    firstname: 'Mariana',
    lastname: 'Santos',
    image: user4,
    department: 'Engenharia',
    company: 'Construtora Lehner-Jacobson',
    phone: '(31) 9 7654-3210',
    email: 'mariana.santos@yahoo.com.br',
    address: 'Rua Oscar Freire, 500, São Paulo, SP, 01426-001',
    notes: 'Especialista em avaliação de imóveis',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
  },
  {
    id: 4,
    firstname: 'Pedro',
    lastname: 'Ferreira',
    image: user5,
    department: 'Suporte',
    company: 'Imobiliária Champlin',
    phone: '(41) 9 8901-2345',
    email: 'pedro.ferreira@outlook.com',
    address: 'Rua Augusta, 1500, São Paulo, SP, 01304-001',
    notes: 'Especialista em locação de imóveis comerciais',
    frequentlycontacted: false,
    starred: true,
    deleted: true,
  },
  {
    id: 5,
    firstname: 'Juliana',
    lastname: 'Costa',
    image: user1,
    department: 'Engenharia',
    company: 'Construtora Balistreri',
    phone: '(51) 9 7890-1234',
    email: 'juliana.costa@gmail.com',
    address: 'Rua Haddock Lobo, 595, São Paulo, SP, 01414-001',
    notes: 'Especialista em projetos de condomínios',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
  },
  {
    id: 6,
    firstname: 'Rafael',
    lastname: 'Almeida',
    image: user2,
    department: 'Suporte',
    company: 'Imobiliária Bernier-Ankunding',
    phone: '(61) 9 8765-4321',
    email: 'rafael.almeida@hotmail.com',
    address: 'Alameda Santos, 1000, São Paulo, SP, 01418-100',
    notes: 'Especialista em documentação imobiliária',
    frequentlycontacted: true,
    starred: false,
    deleted: true,
  },
  {
    id: 7,
    firstname: 'Fernanda',
    lastname: 'Rodrigues',
    image: user3,
    department: 'Suporte',
    company: 'Imobiliária Rosenbaum',
    phone: '(71) 9 9876-5432',
    email: 'fernanda.rodrigues@yahoo.com.br',
    address: 'Rua Bela Cintra, 1200, São Paulo, SP, 01415-001',
    notes: 'Especialista em marketing imobiliário',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 8,
    firstname: 'Lucas',
    lastname: 'Martins',
    image: user4,
    department: 'Vendas',
    company: 'Imobiliária Smith-Romaguera',
    phone: '(81) 9 8901-2345',
    email: 'lucas.martins@outlook.com',
    address: 'Rua Joaquim Floriano, 100, São Paulo, SP, 04534-000',
    notes: 'Especialista em imóveis de alto padrão',
    frequentlycontacted: true,
    starred: true,
    deleted: true,
  },
  {
    id: 9,
    firstname: 'Beatriz',
    lastname: 'Gomes',
    image: user5,
    department: 'Engenharia',
    company: 'Construtora Corwin-Kassulke',
    phone: '(91) 9 7654-3210',
    email: 'beatriz.gomes@gmail.com',
    address: 'Avenida Brigadeiro Faria Lima, 3000, São Paulo, SP, 04538-132',
    notes: 'Especialista em retrofit de edifícios',
    frequentlycontacted: false,
    starred: true,
    deleted: true,
  },
  {
    id: 10,
    firstname: 'Gustavo',
    lastname: 'Pereira',
    image: user2,
    department: 'Suporte',
    company: 'Imobiliária Homenick-Hartmann',
    phone: '(21) 9 8765-4321',
    email: 'gustavo.pereira@hotmail.com',
    address: 'Rua Pamplona, 1000, São Paulo, SP, 01405-001',
    notes: 'Especialista em gestão de condomínios',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 11,
    firstname: 'Camila',
    lastname: 'Souza',
    image: user1,
    department: 'Engenharia',
    company: 'Construtora Gleason',
    phone: '(31) 9 9876-5432',
    email: 'camila.souza@yahoo.com.br',
    address: 'Rua Tabapuã, 500, São Paulo, SP, 04533-001',
    notes: 'Especialista em projetos sustentáveis',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 12,
    firstname: 'Thiago',
    lastname: 'Lima',
    image: user2,
    department: 'Suporte',
    company: 'Imobiliária McKenzie e Filhos',
    phone: '(41) 9 8901-2345',
    email: 'thiago.lima@outlook.com',
    address: 'Rua Amauri, 255, São Paulo, SP, 01448-000',
    notes: 'Especialista em legislação imobiliária',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
  },
  {
    id: 13,
    firstname: 'Isabela',
    lastname: 'Carvalho',
    image: user3,
    department: 'Vendas',
    company: 'Imobiliária Erdman-Moen',
    phone: '(51) 9 7654-3210',
    email: 'isabela.carvalho@gmail.com',
    address: 'Rua Pedroso Alvarenga, 900, São Paulo, SP, 04531-011',
    notes: 'Especialista em imóveis na planta',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 14,
    firstname: 'Felipe',
    lastname: 'Barbosa',
    image: user4,
    department: 'Engenharia',
    company: 'Construtora Fay',
    phone: '(61) 9 8765-4321',
    email: 'felipe.barbosa@hotmail.com',
    address: 'Rua Funchal, 375, São Paulo, SP, 04551-060',
    notes: 'Especialista em inspeção predial',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 15,
    firstname: 'Larissa',
    lastname: 'Ribeiro',
    image: user5,
    department: 'Vendas',
    company: 'Imobiliária Bode-Oberbrunner',
    phone: '(71) 9 9876-5432',
    email: 'larissa.ribeiro@yahoo.com.br',
    address: 'Rua Leopoldo Couto de Magalhães Jr, 700, São Paulo, SP, 04542-000',
    notes: 'Especialista em imóveis de temporada',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
  },
  {
    id: 16,
    firstname: 'Rodrigo',
    lastname: 'Alves',
    image: user1,
    department: 'Suporte',
    company: 'Imobiliária Pagac',
    phone: '(81) 9 8901-2345',
    email: 'rodrigo.alves@outlook.com',
    address: 'Rua Gomes de Carvalho, 1200, São Paulo, SP, 04547-004',
    notes: 'Especialista em regularização de imóveis',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
  },
  {
    id: 17,
    firstname: 'Amanda',
    lastname: 'Fernandes',
    image: user2,
    department: 'Vendas',
    company: 'Imobiliária Predovic e Filhos',
    phone: '(91) 9 7654-3210',
    email: 'amanda.fernandes@gmail.com',
    address: 'Rua Clodomiro Amazonas, 1000, São Paulo, SP, 04537-082',
    notes: 'Especialista em imóveis corporativos',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 18,
    firstname: 'Bruno',
    lastname: 'Cardoso',
    image: user3,
    department: 'Suporte',
    company: 'Imobiliária Graham',
    phone: '(21) 9 8765-4321',
    email: 'bruno.cardoso@hotmail.com',
    address: 'Rua Fidêncio Ramos, 160, São Paulo, SP, 04551-010',
    notes: 'Especialista em avaliação de carteiras imobiliárias',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 19,
    firstname: 'Carolina',
    lastname: 'Pinto',
    image: user4,
    department: 'Vendas',
    company: 'Imobiliária Toy-Ryan',
    phone: '(31) 9 9876-5432',
    email: 'carolina.pinto@yahoo.com.br',
    address: 'Rua Ramos Batista, 444, São Paulo, SP, 04552-020',
    notes: 'Especialista em imóveis rurais',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 20,
    firstname: 'Daniel',
    lastname: 'Moreira',
    image: user5,
    department: 'Suporte',
    company: 'Imobiliária Walsh',
    phone: '(41) 9 8901-2345',
    email: 'daniel.moreira@outlook.com',
    address: 'Rua Olimpíadas, 205, São Paulo, SP, 04551-000',
    notes: 'Especialista em gestão de locações',
    frequentlycontacted: false,
    starred: true,
    deleted: true,
  },
  {
    id: 21,
    firstname: 'Eduarda',
    lastname: 'Teixeira',
    image: user3,
    department: 'Suporte',
    company: 'Imobiliária Romaguera',
    phone: '(51) 9 7654-3210',
    email: 'eduarda.teixeira@gmail.com',
    address: 'Rua Alvorada, 1289, São Paulo, SP, 04550-004',
    notes: 'Especialista em due diligence imobiliária',
    frequentlycontacted: true,
    starred: false,
    deleted: false,
  },
  {
    id: 22,
    firstname: 'Fábio',
    lastname: 'Correia',
    image: user1,
    department: 'Engenharia',
    company: 'Construtora Leuschke',
    phone: '(61) 9 8765-4321',
    email: 'fabio.correia@hotmail.com',
    address: 'Rua Casa do Ator, 275, São Paulo, SP, 04546-001',
    notes: 'Especialista em retrofit sustentável',
    frequentlycontacted: true,
    starred: false,
    deleted: true,
  },
  {
    id: 23,
    firstname: 'Gabriela',
    lastname: 'Mendes',
    image: user2,
    department: 'Vendas',
    company: 'Imobiliária Schumm',
    phone: '(71) 9 9876-5432',
    email: 'gabriela.mendes@yahoo.com.br',
    address: 'Rua Dr. Cardoso de Melo, 1460, São Paulo, SP, 04548-005',
    notes: 'Especialista em imóveis de alto luxo',
    frequentlycontacted: true,
    starred: false,
    deleted: true,
  },
  {
    id: 24,
    firstname: 'Henrique',
    lastname: 'Rocha',
    image: user3,
    department: 'Desenvolvimento de Negócios',
    company: 'Imobiliária Brakus',
    phone: '(81) 9 8901-2345',
    phone: '450-980-6520',
    email: 'Aragondfdf4567@claimab.com',
    address: 'Rua Quatá, 300, São Paulo, SP, 04546-042',
    address: '13 Pent Rd Branford',
    notes: 'Multi-Tiered Hybrid Groupware',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 25,
    firstname: 'Johanna',
    lastname: 'Randel',
    image: user4,
    department: 'Sales',
    company: 'Goyette',
    phone: '120-320-4520',
    email: 'Johanna456@claimab.com',
    address: '5791 S Staghorn Cholla Ct Apache Junction',
    notes: 'Reduced Tangible Project',
    frequentlycontacted: true,
    starred: true,
    deleted: true,
  },
  {
    id: 26,
    firstname: 'Victorina',
    lastname: 'Heinze',
    image: user4,
    department: 'Business Development',
    company: 'Fritsch',
    phone: '452-521-1230',
    email: 'Victorina4545@claimab.com',
    address: '69 El Molino Dr Clayton',
    notes: 'Enhanced Web-Enabled Info-Mediaries',
    frequentlycontacted: false,
    starred: false,
    deleted: true,
  },
  {
    id: 27,
    firstname: 'Kiley',
    lastname: 'Light',
    image: user5,
    department: 'Sales',
    company: 'Langosh',
    phone: '652-452-1230',
    email: 'Kileydfdfd45@claimab.com',
    address: '215 Waterfront Ct Noblesville',
    notes: 'Function-Based Systemic Localareanetwork',
    frequentlycontacted: false,
    starred: true,
    deleted: false,
  },
  {
    id: 28,
    firstname: 'Sanford',
    lastname: 'Delorenzo',
    image: user1,
    department: 'Engineering',
    company: 'Huels',
    phone: '963-652-1230',
    email: 'Delorenzo3456@claimab.com',
    address: '11212 Amber Rd Manistee',
    notes: 'Reactive Transitional Archive',
    frequentlycontacted: true,
    starred: true,
    deleted: false,
  },
  {
    id: 29,
    firstname: 'Hans',
    lastname: 'Strebel',
    image: user2,
    department: 'Sales',
    company: 'Kohler',
    phone: '546-654-1230',
    email: 'Strebel345@claimab.com',
    address: '2009 W Azalea Ave Baker',
    notes: 'Operative Mobile Portal',
    frequentlycontacted: false,
    starred: false,
    deleted: false,
  },
  {
    id: 30,
    firstname: 'Roger',
    lastname: 'Trinidad',
    image: user1,
    department: 'Sales',
    company: 'Kling-Hintz',
    phone: '123-456-7890',
    email: '3mcrz8gmymd@claimab.com',
    address: '203 Dawn Dr, Mount Holly, NC, 28120',
    notes: 'Fundamental Maximized Systemengine',
    frequentlycontacted: false,
    starred: true,
    deleted: true,
  },
];
mock.onGet('/api/data/contacts/ContactsData').reply(() => {
  const contacts = ContactList;
  return [200, JSON.parse(JSON.stringify(contacts))];
});
export default ContactList;
